export const LITERAL_ES = {
  LOGGED_SESSION: {
    TITLE: "¡Bienvenido de nuevo!",
    SUBTITLE: "Genial, estas disfurtando de precios exclusivos.",
  },
  NO_LOGGED_SESSION: {
    TITLE: "¡Precios exclusivos para usuarios registrados!",
    SUBTITLE: "Inicia sesión y accede a ofertas únicas",
  },
  TRIP: {
    FLIGHT: "Vuelo",
    HOTEL: "Hotel",
    TRANSFER: "Transfer",
    TRIP: "Actividad",
    OTHER: "Información importante",
  },
  ACCOUNT: "Mi cuenta",
  FRIENDS: "Invitar amigos",
  SECURE: "Seguridad",
  FAQS: "Preguntas frecuentes",
  ROOM: "Habitación",
  ADULTS: "Adultos",
  CHILDREN: "Niños",
  TRANSPORT: {
    TRAIN: "Tren",
    BUS: "Autobus",
    BOAT: "Barco",
    BIKE: "Bicicleta",
    SCOOTER: "Patinete",
    METRO: "Metro",
    TRAM: "Tranvia",
    UBER: "Uber",
    CABIFY: "Cabify",
    BOLD: "Bold",
    GRAB: "Grab",
    TAXI: "Taxi",
    OTHERS: "Otros",
  },
};
