const LITERALS = {
  BACK: "Atrás",
  GO_BACK: "Volver",
  NEXT: "Siguiente",
  MAIL: "E-mail",
  PHONE: "Teléfono móvil",
  PHONE_NUMBER: "916 024 600",
  NAME: "Nombre",
  SURNAME: "Primer Apellido",
  NATIONALITY: "Nacionalidad",
  PLACEHOLDERTEXT: "Escribe aquí tu",
  DNI: "DNI/NIF",
  SEXO: "Genero",
  BIRTH: "Fecha de Nacimiento",
  CIVIL: "Estado civil",
  VIA_TYPE: "Tipo de vía",
  NAME_TYPE: "Nombre de la vía",
  NUMBER_TYPE: "Número",
  ADITIONALS: "Datos adicionales",
  CLICK_TO_CALL: "Quiero que me llamen",
  ADITIONALS_SUBTEXT: "Si es necesario completa tu dirección.",
  ADITIONALS_PLACEHOLDER: "Portal, bloque, escalera...",
  DOOR: "Piso/Puerta",
  FLOOR: "Nº",
  CLOSE: "Cerrar",
  FLAT_TYPE: "Piso/puerta",
  LOCATION: "Localidad",
  PROVINCE: "Provincia",
  POST_CODE: "Codigo Postal",
  PROFESSION: "Profesión",
  ACTIVITY: "Actividad desempeñada",
  REQUEST_LABEL: "Es un campo obligatorio para continuar",
  REQUEST_PLURAL_LABEL: "Estos campos son obligatorios para continuar",
  DNI_NIE_FORMAT_ERROR: "El DNI/NIF no sigue el formato correcto",
  ERROR_LABEL: "El campo no es correcto",
  NUMBER_VALUE: "El valor introducido tiene que ser de [number] digitos",
  GTM_ACTION: "Funnel Orfandad | Paso",
  MODAL_TITLE: "¡Ups! Algo ha ido mal",
  MODAL_DESCRIPTION: [
    "Puedes volver a intentarlo pulsando ‘reintentar’ o si el problema persiste puedes ponerte en contacto con nosotros en el",
    "**916 024 600**",
  ],
  ACCOUNT: "Mi cuenta",
  FRIENDS: "Invita a tus amigos",
  SECURE: "Seguridad",
  FAQS: "Faqs",
  PASSWORDS_MUST_MATCH: "Las contraseñas deben coincidir",
  REQUEST_OK: "Solicitud enviada correctamente",
  REQUEST_KO: "Error al enviar la solicitud",
};

const SUBMIT = {
  ACCOUNT: "Guardar cambios",
  FRIENDS: "Invita a tus amigos",
  SECURE: "Guardar cambios",
  FAQS: "Guardar cambios",
};

export { LITERALS, SUBMIT };
